#!/bin/bash

# Contents {{{
# _____________

    # 1/ Path
    # 2/ Options
    # 3/ Exports
    # 4/ Aliases
    # 5/ Functions
    # 6/ Completion
    # 7/ Prompt
	# 8/ Fzf
	# 9/ Local

BASHRC_SOURCE=$(readlink -n "${BASH_SOURCE[0]}")
BASHRC_DIR=$(dirname ${BASHRC_SOURCE})

# 1/ Path {{{
# ============

source "${BASHRC_DIR}/bash.d/path.sh"

# 2/ Options {{{
# ==============

source "${BASHRC_DIR}/bash.d/options.sh"

# 3/ Exports {{{
# ==============

source "${BASHRC_DIR}/bash.d/exports.sh"

# 4/ Aliases {{{
# ==============

source "${BASHRC_DIR}/../../aliases"
source "${BASHRC_DIR}/bash.d/aliases.sh"

# 5/ Functions {{{
# ================

source "${BASHRC_DIR}/../../functions"
source "${BASHRC_DIR}/bash.d/functions.sh"

# 6/ Completion {{{
# =================

source "${BASHRC_DIR}/bash.d/completions.sh"

# 7/ Prompt {{{
# =============

source "${BASHRC_DIR}/bash.d/prompt.sh"

# 8/ Fzf {{{
# ==========

# Fuzzy Finder
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# 9/ Local {{{
# ============

BASHRC_LOCAL="${HOME}/.bashrc.local"
[ -r "${BASHRC_LOCAL}" ] && source "${BASHRC_LOCAL}"





