#!/bin/bash
#
# Just in case
#

BASHRC_SOURCE=$(readlink -n "${BASH_SOURCE[0]}")
BASHRC_DIR=$(dirname ${BASHRC_SOURCE})

# Load the shell dotfiles, and then some:
for file in ${BASHRC_DIR}/{path,options,exports,aliases,functions,completions,prompt}.sh; do
  	[ -r "${file}" ] && source "${file}"
done

# Fuzzy Finder
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

BASHRC_LOCAL="${HOME}/.bashrc.local"
[ -r "${BASHRC_LOCAL}" ] && source "${BASHRC_LOCAL}"
